name: Nourishing Fix
favicon: null
layout_spectrum: 0.6140455100685358
typography_spectrum: 0.5246088525746018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.13526178523898125
  lightness: 0.6409095686394721
  saturation: 0.19716339511796832
  rhythmicContrast: 0.8617060689721256
purpose: []
